collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6272401
color:
  saturation: 0.5591398
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#0A0B0E'
    - '#8A9090'
    - '#FCFFFF'
  rhythmicContrast: 0.8289591
layout_spectrum: 0
name: Beta1
